FROM python:3.9-slim

WORKDIR /app
COPY .env ./
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_ENV=production
ENV FLASK_APP=flask_server.py

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]